name: advanced1
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.11
  - osmnx=1.3.0
  - jupyterlab
  - ipykernel
  - folium>=0.14
  - jinja2>=3.1
  - matplotlib>=3.8
  - pandas>=2.1
  - geopandas>=0.14
  - shapely>=2.0
  - poppler
  - numpy>=1.25
  - alphashape>=1.3
  - contextily>=1.4
  - plotly>=5.18
  - mapclassify>=2.6
  - descartes